CREATE SCHEMA IF NOT EXISTS db_costs;

USE db_costs;

DROP TABLE IF EXISTS PROJECT;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS SERVICE;

CREATE TABLE IF NOT EXISTS CATEGORY (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name TEXT NOT NULL
);

CREATE TABLE PROJECT (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name TEXT NOT NULL,
  category_id INT NOT NULL,
  description TEXT,
  created_at TIMESTAMP NOT NULL,
  budget INT NOT NULL,
  FOREIGN KEY(category_id) REFERENCES CATEGORY(id)
);


CREATE TABLE SERVICE (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name TEXT NOT NULL,
  project_id INT NOT NULL,
  description TEXT,
  created_at TIMESTAMP NOT NULL,
  value INT NOT NULL,
  FOREIGN KEY(project_id) REFERENCES PROJECT(id)
);