FROM mysql:latest

EXPOSE 3306

ENV MYSQL_ROOT_PASSWORD=project-costs
ENV MYSQL_DATABASE=db_costs
ENV MYSQL_USER=project-costs
ENV MYSQL_PASSWORD=project-costs
ENV MYSQL_AUTH_PLUGIN=mysql_native_password

COPY ./setup.sql /docker-entrypoint-initdb.d/
